# base image
FROM node:lts-alpine

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies


COPY . .
RUN npm install
RUN npm install @vue/cli@3.7.0 -g

EXPOSE 8080
# start app
CMD ["npm", "run", "dev"]
